version: "3.8"

services:
    stocks-api:
        build: .
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=sqlite:///./data/stocks.db
            - POLYGON_API_KEY=bs1n5Vdqoi_NOvmCZ_85rrcvtFnYN3vm
            - REDIS_URL=redis://redis:6379
        volumes:
            - ./data:/app/data
        depends_on:
            - redis
        restart: unless-stopped

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        restart: unless-stopped

    worker:
        build: .
        command: celery -A app.tasks worker --loglevel=info
        environment:
            - DATABASE_URL=sqlite:///./data/stocks.db
            - POLYGON_API_KEY=bs1n5Vdqoi_NOvmCZ_85rrcvtFnYN3vm
            - REDIS_URL=redis://redis:6379
            - REDIS_DB=0
        volumes:
            - ./data:/app/data
        depends_on:
            - redis
        restart: unless-stopped

    scheduler:
        build: .
        command: celery -A app.tasks beat --loglevel=info
        environment:
            - REDIS_URL=redis://redis:6379
            - REDIS_DB=0
        depends_on:
            - redis
        restart: unless-stopped

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"
        depends_on:
            - redis
        profiles:
            - monitoring
        restart: unless-stopped
